"""
Example: Testing Setup Wizard Output
=====================================

This example demonstrates what the setup wizard will create in your .env file.
"""

# Example .env output after running: notion-docs setup

# ============================================
# SETUP WIZARD OUTPUT EXAMPLES
# ============================================

# Example 1: Database Mode (Single Database)
"""
# Notion Docs Synapse Configuration
# Generated by setup wizard

# Notion Integration
NOTION_TOKEN=secret_abc123def456ghi789jkl012mno345pqr678stu901vwx234yz
NOTION_DB_IT=2906d85c-ec32-80d3-a930-d3e0be89dd69
NOTION_DB_EN=2906d85c-ec32-80d3-a930-d3e0be89dd69

# LLM Provider (choose one)
LLM_PROVIDER=openai
# OPENAI_API_KEY=your-key-here
# ANTHROPIC_API_KEY=your-key-here
# GOOGLE_API_KEY=your-key-here
"""

# Example 2: Database Mode (Separate Databases)
"""
# Notion Docs Synapse Configuration
# Generated by setup wizard

# Notion Integration
NOTION_TOKEN=secret_abc123def456ghi789jkl012mno345pqr678stu901vwx234yz
NOTION_DB_IT=2906d85c-ec32-80d3-a930-d3e0be89dd69
NOTION_DB_EN=2906d85c-ec32-80d4-9390-d403c08086e2

# LLM Provider (choose one)
LLM_PROVIDER=openai
# OPENAI_API_KEY=your-key-here
"""

# Example 3: Pages Mode
"""
# Notion Docs Synapse Configuration
# Generated by setup wizard

# Notion Integration
NOTION_TOKEN=secret_abc123def456ghi789jkl012mno345pqr678stu901vwx234yz
NOTION_PAGE_IT=2236d85c-ec32-80d9-8831-ec4f51d13ba0
NOTION_PAGE_EN=2236d85c-ec32-80d5-8831-ec4f51d13ba1

# LLM Provider (choose one)
LLM_PROVIDER=openai
# OPENAI_API_KEY=your-key-here
"""

# ============================================
# PROGRAMMATIC USAGE
# ============================================

def test_wizard_programmatically():
    """Example of running wizard programmatically (for testing)."""
    from notion_scriba.setup_wizard import NotionSetupWizard
    
    wizard = NotionSetupWizard()
    
    # Note: This will prompt for user input interactively
    # For automated testing, you'd need to mock stdin
    
    print("To run wizard:")
    print("  python -m notion_scriba.setup_wizard")
    print("  # or")
    print("  scriba-setup")


if __name__ == "__main__":
    print(__doc__)
    print("\n🔧 Example .env outputs shown above")
    print("\n🚀 To run the wizard:")
    print("   notion-docs setup")
    print("   # or")
    print("   notion-docs-setup")
